apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-seccomp-runtime-default
  annotations:
    policies.kyverno.io/title: Require RuntimeDefault seccomp
    policies.kyverno.io/category: Pod Security
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-runtime-default
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Pods must use seccompProfile.type RuntimeDefault."
        pattern:
          spec:
            securityContext:
              seccompProfile:
                type: RuntimeDefault

